### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by kinggreat24** [irapkaist/removert#1]
I got the following errors when compiling under ROS Kinetic in Ubuntu-16.04, can you tell me the version of PCL?
`Removerter.cpp:(.text+0x3271): undefined reference to `pcl::octree::OctreePointCloud<pcl::PointXYZI, pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty> >::OctreePointCloud(double)'
Removerter.cpp:(.text+0x3319): undefined reference to `pcl::octree::OctreePointCloud<pcl::PointXYZI, pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty> >::defineBoundingBox()'
Removerter.cpp:(.text+0x3321): undefined reference to `pcl::octree::OctreePointCloud<pcl::PointXYZI, pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty> >::addPointsFromInputCloud()'
Removerter.cpp:(.text+0x3461): undefined reference to `pcl::octree::OctreePointCloud<pcl::PointXYZI, pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty> >::~OctreePointCloud()'
Removerter.cpp:(.text+0x362a): undefined reference to `pcl::octree::OctreePointCloud<pcl::PointXYZI, pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty> >::~OctreePointCloud()'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o: In function `pcl::octree::OctreePointCloudVoxelCentroid<pcl::PointXYZI, pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty>::addPointIdx(int)':
Removerter.cpp:(.text._ZN3pcl6octree29OctreePointCloudVoxelCentroidINS_9PointXYZIENS0_38OctreePointCloudVoxelCentroidContainerIS2_EENS0_20OctreeContainerEmptyEE11addPointIdxEi[_ZN3pcl6octree29OctreePointCloudVoxelCentroidINS_9PointXYZIENS0_38OctreePointCloudVoxelCentroidContainerIS2_EENS0_20OctreeContainerEmptyEE11addPointIdxEi]+0x4b): undefined reference to `pcl::octree::OctreePointCloud<pcl::PointXYZI, pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty> >::adoptBoundingBoxToPoint(pcl::PointXYZI const&)'
Removerter.cpp:(.text._ZN3pcl6octree29OctreePointCloudVoxelCentroidINS_9PointXYZIENS0_38OctreePointCloudVoxelCentroidContainerIS2_EENS0_20OctreeContainerEmptyEE11addPointIdxEi[_ZN3pcl6octree29OctreePointCloudVoxelCentroidINS_9PointXYZIENS0_38OctreePointCloudVoxelCentroidContainerIS2_EENS0_20OctreeContainerEmptyEE11addPointIdxEi]+0x59): undefined reference to `pcl::octree::OctreePointCloud<pcl::PointXYZI, pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty> >::genOctreeKeyforPoint(pcl::PointXYZI const&, pcl::octree::OctreeKey&) const'
Removerter.cpp:(.text._ZN3pcl6octree29OctreePointCloudVoxelCentroidINS_9PointXYZIENS0_38OctreePointCloudVoxelCentroidContainerIS2_EENS0_20OctreeContainerEmptyEE11addPointIdxEi[_ZN3pcl6octree29OctreePointCloudVoxelCentroidINS_9PointXYZIENS0_38OctreePointCloudVoxelCentroidContainerIS2_EENS0_20OctreeContainerEmptyEE11addPointIdxEi]+0x73): undefined reference to `pcl::octree::OctreeBase<pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty>::createLeafRecursive(pcl::octree::OctreeKey const&, unsigned int, pcl::octree::OctreeBranchNode<pcl::octree::OctreeContainerEmpty>*, pcl::octree::OctreeLeafNode<pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI> >*&, pcl::octree::OctreeBranchNode<pcl::octree::OctreeContainerEmpty>*&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o: In function `pcl::octree::OctreePointCloudVoxelCentroid<pcl::PointXYZI, pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty>::~OctreePointCloudVoxelCentroid()':
Removerter.cpp:(.text._ZN3pcl6octree29OctreePointCloudVoxelCentroidINS_9PointXYZIENS0_38OctreePointCloudVoxelCentroidContainerIS2_EENS0_20OctreeContainerEmptyEED2Ev[_ZN3pcl6octree29OctreePointCloudVoxelCentroidINS_9PointXYZIENS0_38OctreePointCloudVoxelCentroidContainerIS2_EENS0_20OctreeContainerEmptyEED5Ev]+0xf): undefined reference to `pcl::octree::OctreePointCloud<pcl::PointXYZI, pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty> >::~OctreePointCloud()'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o: In function `pcl::octree::OctreePointCloudVoxelCentroid<pcl::PointXYZI, pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty>::~OctreePointCloudVoxelCentroid()':
Removerter.cpp:(.text._ZN3pcl6octree29OctreePointCloudVoxelCentroidINS_9PointXYZIENS0_38OctreePointCloudVoxelCentroidContainerIS2_EENS0_20OctreeContainerEmptyEED0Ev[_ZN3pcl6octree29OctreePointCloudVoxelCentroidINS_9PointXYZIENS0_38OctreePointCloudVoxelCentroidContainerIS2_EENS0_20OctreeContainerEmptyEED5Ev]+0x13): undefined reference to `pcl::octree::OctreePointCloud<pcl::PointXYZI, pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty> >::~OctreePointCloud()'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl6octree29OctreePointCloudVoxelCentroidINS_9PointXYZIENS0_38OctreePointCloudVoxelCentroidContainerIS2_EENS0_20OctreeContainerEmptyEEE[_ZTVN3pcl6octree29OctreePointCloudVoxelCentroidINS_9PointXYZIENS0_38OctreePointCloudVoxelCentroidContainerIS2_EENS0_20OctreeContainerEmptyEEE]+0x38): undefined reference to `pcl::octree::OctreePointCloud<pcl::PointXYZI, pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreePointCloudVoxelCentroidContainer<pcl::PointXYZI>, pcl::octree::OctreeContainerEmpty> >::genOctreeKeyForDataT(int const&, pcl::octree::OctreeKey&) const'
collect2: error: ld returned 1 exit status
removert/CMakeFiles/removert_removert.dir/build.make:539: recipe for target '/home/kinggreat24/direct_lidar_align_ws/devel/lib/removert/removert_removert' failed
make[2]: *** [/home/kinggreat24/direct_lidar_align_ws/devel/lib/removert/removert_removert] Error 1
CMakeFiles/Makefile2:3810: recipe for target 'removert/CMakeFiles/removert_removert.dir/all' failed
make[1]: *** [removert/CMakeFiles/removert_removert.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by gisbi-kim** [comment]
I'm using PCL 1.8.1 and the program was tested under Ubuntu18.04 ROS melodic.

**Comment by kinggreat24** [comment]
> I'm using PCL 1.8.1 and the program was tested under Ubuntu18.04 ROS melodic.

Thank you for your reply and  I have compiled success under Ubuntu16.04.

**Comment by gisbi-kim** [comment]
@kinggreat24 good! 
I close this issue.

**Comment by narutojxl** [comment]
Hi @kinggreat24, when you build pcl-1.8.1 from source, 
* Did you use the default system installed eigen 3.2.92 ?  Which specifed in  `/usr/include/eigen3/Eigen/src/Core/util/Macros.h`.
* Which version of gcc you used when building pcl-1.8.1? Because build removert need gcc >=8.0

I use the system installed eigen 3.2.92 and gcc 5.4.0 build and install OK, when use gcc-8.0 to build removert, it can find the locally installed pcl-1.8.1, but  the error `undefined reference to pcl::octree::OctreePointCloud` still exist.

**Comment by kinggreat24** [comment]
> Hi @kinggreat24, when you build pcl-1.8.1 from source,
> 
> * Did you use the default system installed eigen 3.2.92 ?  Which specifed in  `/usr/include/eigen3/Eigen/src/Core/util/Macros.h`.
> * Which version of gcc you used when building pcl-1.8.1? Because build removert need gcc >=8.0
> 
> I use the system installed eigen 3.2.92 and gcc 5.4.0 build and install OK, when use gcc-8.0 to build removert, it can find the locally installed pcl-1.8.1, but the error `undefined reference to pcl::octree::OctreePointCloud` still exist.

- Eigen version I used is Eigen3.2.92
- gcc version is gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
I use c++14 instead of c++17.

**Comment by narutojxl** [comment]
Hi @kinggreat24, thanks for your info. Use c++14 will occur `filesystem` error when i tried. There is something weird, because the workflow is the same with you.

**Comment by kinggreat24** [comment]
> Hi @kinggreat24, thanks for your info. Use c++14 will occur `filesystem` error when i tried. There is something weird, because the workflow is the same with you.
I reimplemented the "filesystem" related code which implemented via c++17, and the code  uploaded just now to the git, you may try this.
https://github.com/kinggreat24/removert.git

**Comment by narutojxl** [comment]
Hi @kinggreat24 and @gisbi-kim,
I compared kinggreat24's version and the raw version, when i  comment ros package `pcl_conversions` in the CMakeLists.txt on ubuntu16.04, use gcc-8.4.0 and pcl-1.8.1, which built with gcc-5.4.0 and system's eigen 3.2.92,  can build the raw removert OK. 
BTW, use gcc-5.4.0 and gcc-8.4.0 also build kinggreat24's version OK.
>
	find_package(catkin REQUIRED COMPONENTS
	  tf
	  roscpp
	  rospy
	  cv_bridge
	  # pcl library
	  # pcl_conversions
	  # msgs
	  std_msgs
	  sensor_msgs
	  geometry_msgs
	  nav_msgs
	  message_generation
	  image_transport
	)

**Comment by vernon97** [comment]
> Hi @kinggreat24 and @gisbi-kim,
> I compared kinggreat24's version and the raw version, when i comment ros package `pcl_conversions` in the CMakeLists.txt on ubuntu16.04, use gcc-8.4.0 and pcl-1.8.1, which built with gcc-5.4.0 and system's eigen 3.2.92, can build the raw removert OK.
> BTW, use gcc-5.4.0 and gcc-8.4.0 also build kinggreat24's version OK.
> 
> > 
> 
> ```
> find_package(catkin REQUIRED COMPONENTS
>   tf
>   roscpp
>   rospy
>   cv_bridge
>   # pcl library
>   # pcl_conversions
>   # msgs
>   std_msgs
>   sensor_msgs
>   geometry_msgs
>   nav_msgs
>   message_generation
>   image_transport
> )
> ```

Thank you for your reply. I follow your instruction and then compile successfully.
Btw, the version of PCL here is 1.9.1, which is built from the source code.

**Comment by ikhann** [comment]
Hi! The solution to install Multiple GCC Versions helped me with the same issue.
My workspace: 
- Ubuntu 18.04
- ROS Melodic
- Eigen 3.3.4
- PCL 1.8

First, add the ubuntu-toolchain-r/test PPA to your system with:
```
sudo apt install software-properties-common
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
```

Install the GCC and G++ versions by typing:
```
sudo apt install software-properties-common
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
```

The commands below will configure alternative for each version and associate a priority with it. The default version is the one with the highest priority, in our case that is gcc-8:
```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7
```

Later if you want to change the default version use the update-alternatives command:
```
sudo update-alternatives --config gcc
```

```
There are 2 choices for the alternative gcc (providing /usr/bin/gcc).

  Selection    Path            Priority   Status
------------------------------------------------------------
* 0            /usr/bin/gcc-8   80        auto mode
  1            /usr/bin/gcc-7   70        manual mode
  2            /usr/bin/gcc-8   80        manual mode

Press <enter> to keep the current choice[*], or type selection number: 
```
You will be presented with a list of all installed GCC versions on your Ubuntu system. Enter the number of the version you want to be used as a default and press Enter.

The command will create symbolic links to the specific versions of GCC and G++.

**Comment by AnOrdinaryUsser** [comment]
Hi, I'm new to ROS and there are a few things I don't know. I am trying to make my D415 camera detect obstacles using the PCL package. 
I have made the following code:

```c
#include<pcl_conversions/pcl_conversions.h>
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>
#include <pcl/octree/octree_search.h>


void cameraCallback(const sensor_msgs::PointCloud2::ConstPtr& input_cloud) {

    // Convert PointCloud2 message to PointCloud<PointT> object
    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
    pcl::fromROSMsg(*input_cloud, *cloud);

    // Create OctreePointCloudSearch object with desired resolution
    // More resolution, better performance
    pcl::octree::OctreePointCloudSearch<pcl::PointXYZ> octree(0.01);
    octree.setInputCloud(cloud);
    octree.addPointsFromInputCloud();

    // Iterate over points and find neighboring points within a certain radius
    pcl::IndicesPtr indices(new std::vector<int>);
    std::vector<int> pointIdxRadiusSearch;
    std::vector<float> pointRadiusSquaredDistance;
    float radius = 0.1; // desired radius
    int min_neighbors = 5; // desired minimum number of neighbors
    int max_nn = 5;
    //float min_depth = 0.1;
    //float max_depth = 1.5;
    //pcl::octree::OctreeDepthRestriction<pcl::PointXYZ>::Ptr depth_constraint(new pcl::octree::OctreeDepthRestriction<pcl::PointXYZ>(min_depth, max_depth));
    pcl::PointCloud<pcl::PointXYZ>::Ptr group(new pcl::PointCloud<pcl::PointXYZ>);
    for (int i = 0; i < cloud->points.size(); i++)
    {
        if (octree.radiusSearch(cloud->points[i], radius, pointIdxRadiusSearch, pointRadiusSquaredDistance, max_nn) > min_neighbors)
        {
            for (int j = 0; j < pointIdxRadiusSearch.size(); j++)
            {
                group->points.push_back(cloud->points[pointIdxRadiusSearch[j]]);
                indices->push_back(pointIdxRadiusSearch[j]);
            }
        }
    }

    // Publish the group of points as a PointCloud2 message
    sensor_msgs::PointCloud2 output_cloud;
    pcl::toROSMsg(*group, output_cloud);
    output_cloud.header.frame_id = input_cloud->header.frame_id;
    output_cloud.header.stamp = input_cloud->header.stamp;
    pubCameraCol.publish(output_cloud);

}
```

I have added the following packages to my workspace in ROS:
- pcl_conversions
- pcl_ros
- perception_pcl

My problem is that when I run the catkin_make command I get the following error regarding where I have included that code:

```bash
CMakeFiles/lidar_process.dir/src/lidar_process.cpp.o: In function `cameraCallback(boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&)':
lidar_process.cpp:(.text+0x1210): undefined reference to `pcl::octree::OctreePointCloud<pcl::PointXYZ, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty> >::addPointsFromInputCloud()'
lidar_process.cpp:(.text+0x12ec): undefined reference to `pcl::octree::OctreePointCloudSearch<pcl::PointXYZ, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty>::radiusSearch(pcl::PointXYZ const&, double, std::vector<int, std::allocator<int> >&, std::vector<float, std::allocator<float> >&, unsigned int) const'
CMakeFiles/lidar_process.dir/src/lidar_process.cpp.o: In function `pcl::octree::OctreePointCloudSearch<pcl::PointXYZ, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty>::OctreePointCloudSearch(double)':
lidar_process.cpp:(.text._ZN3pcl6octree22OctreePointCloudSearchINS_8PointXYZENS0_27OctreeContainerPointIndicesENS0_20OctreeContainerEmptyEEC2Ed[_ZN3pcl6octree22OctreePointCloudSearchINS_8PointXYZENS0_27OctreeContainerPointIndicesENS0_20OctreeContainerEmptyEEC5Ed]+0x18): undefined reference to `pcl::octree::OctreePointCloud<pcl::PointXYZ, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty> >::OctreePointCloud(double)'
CMakeFiles/lidar_process.dir/src/lidar_process.cpp.o: In function `pcl::octree::OctreePointCloudSearch<pcl::PointXYZ, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty>::~OctreePointCloudSearch()':
lidar_process.cpp:(.text._ZN3pcl6octree22OctreePointCloudSearchINS_8PointXYZENS0_27OctreeContainerPointIndicesENS0_20OctreeContainerEmptyEED2Ev[_ZN3pcl6octree22OctreePointCloudSearchINS_8PointXYZENS0_27OctreeContainerPointIndicesENS0_20OctreeContainerEmptyEED5Ev]+0x20): undefined reference to `pcl::octree::OctreePointCloud<pcl::PointXYZ, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty> >::~OctreePointCloud()'
CMakeFiles/lidar_process.dir/src/lidar_process.cpp.o: In function `void pcl::detail::FieldMapper<pcl::PointXYZ>::operator()<pcl::fields::x>()':
lidar_process.cpp:(.text._ZN3pcl6detail11FieldMapperINS_8PointXYZEEclINS_6fields1xEEEvv[_ZN3pcl6detail11FieldMapperINS_8PointXYZEEclINS_6fields1xEEEvv]+0x1b0): undefined reference to `pcl::console::print(pcl::console::VERBOSITY_LEVEL, char const*, ...)'
CMakeFiles/lidar_process.dir/src/lidar_process.cpp.o: In function `void pcl::detail::FieldMapper<pcl::PointXYZ>::operator()<pcl::fields::y>()':
lidar_process.cpp:(.text._ZN3pcl6detail11FieldMapperINS_8PointXYZEEclINS_6fields1yEEEvv[_ZN3pcl6detail11FieldMapperINS_8PointXYZEEclINS_6fields1yEEEvv]+0x1b4): undefined reference to `pcl::console::print(pcl::console::VERBOSITY_LEVEL, char const*, ...)'
CMakeFiles/lidar_process.dir/src/lidar_process.cpp.o: In function `void pcl::detail::FieldMapper<pcl::PointXYZ>::operator()<pcl::fields::z>()':
lidar_process.cpp:(.text._ZN3pcl6detail11FieldMapperINS_8PointXYZEEclINS_6fields1zEEEvv[_ZN3pcl6detail11FieldMapperINS_8PointXYZEEclINS_6fields1zEEEvv]+0x1b4): undefined reference to `pcl::console::print(pcl::console::VERBOSITY_LEVEL, char const*, ...)'
CMakeFiles/lidar_process.dir/src/lidar_process.cpp.o:(.data.rel.ro._ZTVN3pcl6octree22OctreePointCloudSearchINS_8PointXYZENS0_27OctreeContainerPointIndicesENS0_20OctreeContainerEmptyEEE[_ZTVN3pcl6octree22OctreePointCloudSearchINS_8PointXYZENS0_27OctreeContainerPointIndicesENS0_20OctreeContainerEmptyEEE]+0x30): undefined reference to `pcl::octree::OctreePointCloud<pcl::PointXYZ, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty> >::addPointIdx(int)'
CMakeFiles/lidar_process.dir/src/lidar_process.cpp.o:(.data.rel.ro._ZTVN3pcl6octree22OctreePointCloudSearchINS_8PointXYZENS0_27OctreeContainerPointIndicesENS0_20OctreeContainerEmptyEEE[_ZTVN3pcl6octree22OctreePointCloudSearchINS_8PointXYZENS0_27OctreeContainerPointIndicesENS0_20OctreeContainerEmptyEEE]+0x38): undefined reference to `pcl::octree::OctreePointCloud<pcl::PointXYZ, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty> >::genOctreeKeyForDataT(int const&, pcl::octree::OctreeKey&) const'
collect2: error: ld returned 1 exit status
hybrid_version/CMakeFiles/lidar_process.dir/build.make:115: recipe for target '/home/cartteclab/combined/devel/lib/hybrid_version/lidar_process' failed
make[2]: *** [/home/cartteclab/combined/devel/lib/hybrid_version/lidar_process] Error 1
CMakeFiles/Makefile2:2411: recipe for target 'hybrid_version/CMakeFiles/lidar_process.dir/all' failed
make[1]: *** [hybrid_version/CMakeFiles/lidar_process.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
