### ISSUE TITLE
An error occurred while I was running the  kitti dataset，Which version of PCL library do you use？

### ISSUE THREAD

**Issue by qijixiang** [irapkaist/removert#10]
Thank you very much for your excellent work.A few errors occurred while I was running your algorithm.
So I added some printing instructions to find out where the error was,As is shown in.

![1111](https://user-images.githubusercontent.com/55644039/115558917-c8806400-a2e5-11eb-9058-cbdb2b023176.png)
I use "cout<<"b*"<<endl;" to find the error. So I changed the code a little bit：
![222](https://user-images.githubusercontent.com/55644039/115560296-05992600-a2e7-11eb-9cf6-fe29e10c5b96.png)
That means it was the sentence "     octree.addPointsFromInputCloud();" that caused the error
Why does this happen? Has anyone come across it? Is it because I have the wrong version of PCL library？
I use PCL 1.8

**Comment by Cxz-dev** [comment]
Hi！I got the error too，can you give me some advice？Thank u

**Comment by DeepDuke** [comment]
Hi！I got the error too，can you give me some advice？Thank u
