### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by huangsiyuan0717** [irapkaist/removert#12]
When I compiled the program meet some error as the follows:
![Screenshot from 2021-10-26 16-58-21](https://user-images.githubusercontent.com/69231540/138845749-1d1a1558-38a0-40ad-bb08-c96e3df03f04.png)
I changed to the gcc to 8.4.0 did't work

My software environment as the follows:
ubuntu 18.04  ROS Melodic
eigen: 3.3.4
opencv: 3.4.0
pcl: 1.8.1

**Comment by ikhann** [comment]
https://github.com/irapkaist/removert/issues/1
