### ISSUE TITLE
How do you get mesh representation

### ISSUE THREAD

**Issue by Beastmaster** [irapkaist/removert#13]
I "Further Improvements" section, a beautiful mesh representation of scene could be found. How do you get these mesh?

**Comment by gisbi-kim** [comment]
hi, @Beastmaster 
I think meshing (or surface reconstruction) is the next promising task and desired for both academia and industry
but at this moment, I think converting pointcloud to mesh is another research topic.   

or I guess you can use existing tools such as cloud compare https://www.youtube.com/watch?v=m43usERF33M
