### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by pk1996** [irapkaist/removert#17]
Hi

Thank you for this repo!

I have the following error when I try running your code (actually a variant for C++14 - https://github.com/kinggreat24/removert).
Nevertheless, any idea what could be causing this error?

I also wanted to confirm if I am using the right data. So for the point cloud, I download the 09 kitti sequence from here 
http://www.cvlibs.net/datasets/kitti/raw_data.php and for the pose, I used the ground-truth pose given www.cvlibs.net/datasets/kitti/eval_odometry.php. I know I can use LiDAR odometry or SLAM algorithm you mentioned but this technically is the output I'd get right?

Many thanks!

**Comment by ZhaZhaJ** [comment]
![image](https://user-images.githubusercontent.com/64353489/162367697-579d266b-62d1-4caf-aae5-103818d62c84.png)

hi!
Did you solve this problem ?

**Comment by ZhaZhaJ** [comment]
thanks！
I solved my question.
