### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by tub-sgg** [irapkaist/removert#18]
Operating Sys:18.04
ROS version: melodic
gcc -version:8.0

/usr/bin/ld: warning: libboost_thread.so.1.65.1, needed by /opt/ros/melodic/lib/libroscpp.so, may conflict with libboost_thread.so.1.78.0
/usr/bin/ld: warning: libboost_chrono.so.1.65.1, needed by /opt/ros/melodic/lib/libroscpp.so, may conflict with libboost_chrono.so.1.78.0
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o: In function `Removerter::parseMapPointcloudSubsetUsingPtIdx(std::vector<int, std::allocator<int> >&, boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> >&)':
Removerter.cpp:(.text+0x6af2): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setInputCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> const> const&)'
Removerter.cpp:(.text+0x6b0c): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > > const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o: In function `Removerter::parsePointcloudSubsetUsingPtIdx(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> > const&, std::vector<int, std::allocator<int> >&, boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> >&)':
Removerter.cpp:(.text+0x6e6b): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setInputCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> const> const&)'
Removerter.cpp:(.text+0x6e85): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > > const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o: In function `Removerter::parseStaticMapPointcloudUsingPtIdx(std::vector<int, std::allocator<int> >&)':
Removerter.cpp:(.text+0x708d): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setInputCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> const> const&)'
Removerter.cpp:(.text+0x70a7): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > > const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o: In function `Removerter::parseDynamicMapPointcloudUsingPtIdx(std::vector<int, std::allocator<int> >&)':
Removerter.cpp:(.text+0x72ad): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setInputCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> const> const&)'
Removerter.cpp:(.text+0x72c7): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > > const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o: In function `Removerter::readValidScans()':
Removerter.cpp:(.text+0xf087): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setInputCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> const> const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl11KdTreeFLANNINS_9PointXYZIEN5flann9L2_SimpleIfEEEE[_ZTVN3pcl11KdTreeFLANNINS_9PointXYZIEN5flann9L2_SimpleIfEEEE]+0x10): undefined reference to `pcl::KdTreeFLANN<pcl::PointXYZI, flann::L2_Simple<float> >::setInputCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> const> const&, boost::shared_ptr<std::vector<int, std::allocator<int> > const> const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl7PCLBaseINS_9PointXYZIEEE[_ZTVN3pcl7PCLBaseINS_9PointXYZIEEE]+0x20): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setInputCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> const> const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl7PCLBaseINS_9PointXYZIEEE[_ZTVN3pcl7PCLBaseINS_9PointXYZIEEE]+0x28): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > > const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl7PCLBaseINS_9PointXYZIEEE[_ZTVN3pcl7PCLBaseINS_9PointXYZIEEE]+0x30): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > const> const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl7PCLBaseINS_9PointXYZIEEE[_ZTVN3pcl7PCLBaseINS_9PointXYZIEEE]+0x38): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<pcl::PointIndices const> const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl6FilterINS_9PointXYZIEEE[_ZTVN3pcl6FilterINS_9PointXYZIEEE]+0x20): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setInputCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> const> const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl6FilterINS_9PointXYZIEEE[_ZTVN3pcl6FilterINS_9PointXYZIEEE]+0x28): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > > const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl6FilterINS_9PointXYZIEEE[_ZTVN3pcl6FilterINS_9PointXYZIEEE]+0x30): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > const> const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl6FilterINS_9PointXYZIEEE[_ZTVN3pcl6FilterINS_9PointXYZIEEE]+0x38): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<pcl::PointIndices const> const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl9VoxelGridINS_9PointXYZIEEE[_ZTVN3pcl9VoxelGridINS_9PointXYZIEEE]+0x20): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setInputCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> const> const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl9VoxelGridINS_9PointXYZIEEE[_ZTVN3pcl9VoxelGridINS_9PointXYZIEEE]+0x28): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > > const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl9VoxelGridINS_9PointXYZIEEE[_ZTVN3pcl9VoxelGridINS_9PointXYZIEEE]+0x30): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > const> const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl9VoxelGridINS_9PointXYZIEEE[_ZTVN3pcl9VoxelGridINS_9PointXYZIEEE]+0x38): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<pcl::PointIndices const> const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl13FilterIndicesINS_9PointXYZIEEE[_ZTVN3pcl13FilterIndicesINS_9PointXYZIEEE]+0x20): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setInputCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> const> const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl13FilterIndicesINS_9PointXYZIEEE[_ZTVN3pcl13FilterIndicesINS_9PointXYZIEEE]+0x28): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > > const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl13FilterIndicesINS_9PointXYZIEEE[_ZTVN3pcl13FilterIndicesINS_9PointXYZIEEE]+0x30): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > const> const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl13FilterIndicesINS_9PointXYZIEEE[_ZTVN3pcl13FilterIndicesINS_9PointXYZIEEE]+0x38): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<pcl::PointIndices const> const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl14ExtractIndicesINS_9PointXYZIEEE[_ZTVN3pcl14ExtractIndicesINS_9PointXYZIEEE]+0x20): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setInputCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> const> const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl14ExtractIndicesINS_9PointXYZIEEE[_ZTVN3pcl14ExtractIndicesINS_9PointXYZIEEE]+0x28): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > > const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl14ExtractIndicesINS_9PointXYZIEEE[_ZTVN3pcl14ExtractIndicesINS_9PointXYZIEEE]+0x30): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > const> const&)'
CMakeFiles/removert_removert.dir/src/Removerter.cpp.o:(.data.rel.ro._ZTVN3pcl14ExtractIndicesINS_9PointXYZIEEE[_ZTVN3pcl14ExtractIndicesINS_9PointXYZIEEE]+0x38): undefined reference to `pcl::PCLBase<pcl::PointXYZI>::setIndices(boost::shared_ptr<pcl::PointIndices const> const&)'
collect2: error: ld returned 1 exit status
removert/CMakeFiles/removert_removert.dir/build.make:673: recipe for target '/home/alex/Documents/WorkingArea/TEST_CODE/removert/catkin/removert_ws/devel/lib/removert/removert_removert' failed
make[2]: *** [/home/alex/Documents/WorkingArea/TEST_CODE/removert/catkin/removert_ws/devel/lib/removert/removert_removert] Error 1
CMakeFiles/Makefile2:1954: recipe for target 'removert/CMakeFiles/removert_removert.dir/all' failed
make[1]: *** [removert/CMakeFiles/removert_removert.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed

**Comment by arjunskumar** [comment]
@tub-sgg you may need to downgrade your boost version to 1.65

**Comment by tub-sgg** [comment]
> @tub-sgg you may need to downgrade your boost version to 1.65

I found the issue.I have installed PCL(1.11) library seperatly, so there is a conflict with ROS which is compatible with PCL1.8

**Comment by arjunskumar** [comment]
@tub-sgg PCL 1.11 uses  boost v1.78, btw thanks for the info
