### ISSUE TITLE
roslaunch removert run_scliosam.launch    --------terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by ZhaZhaJ** [irapkaist/removert#25]
![image](https://user-images.githubusercontent.com/64353489/162368127-d8e5fa89-dd55-4317-8cc8-c9b651a97046.png)

**Comment by MIke-1118** [comment]
Excuse me. I met this error too. Have you solved it ?

**Comment by ZhaZhaJ** [comment]
Sorry, I don't remember if i solved this problem.

**Comment by MIke-1118** [comment]
This problem has troubled me for a long time. I see that you wrote under another question 17 that you solved this problem. May I trouble you to think again?

**Comment by ZhaZhaJ** [comment]
I uploaded the code that has worked before, I hope it can help you.    //https://github.com/firstn01/removert_w/tree/master
