### ISSUE TITLE
some questions about removert?

### ISSUE THREAD

**Issue by crankler** [irapkaist/removert#3]
hi， gisbi-kim， Thank you for your shared code about dynamic remove.
I try to use your code and Youtube video to implement this  demo, but there appear a few problems that confused me, 
such as:
1. The kitti path:   I can get "sequence_scan_dir" in kitti dataset, but there can't find **_"poses.txt"_** in the "sequence_pose_path",
The data only  I can find which locate in "../2011_09_26/2011_09_26_drive_0009_sync/velodyne_points/data/*.bin" and 
"../2011_09_26/2011_09_26_drive_0009_sync/velodyne_points/oxts/*.txt"

2.  It seems that function “revertOnce”  need to be reedit, dose it right? how's the difference between the exist of this function?

3. Does "scansideRemovalForEachScanAndSaveThem"  is the BR function in your paper?

Thank you for your reply！

**Comment by gisbi-kim** [comment]
Thank you for your interest in our work. 

The answeres are :
1. Did you download the dataset via "odometry" tab? http://www.cvlibs.net/datasets/kitti/eval_odometry.php -- the poses are available by clicking the "Download odometry ground truth poses (4 MB)" / (but I note that as already wrote in the paper, not the GT poses, but odometry poses (have a little error) can be used for our removing task). 

2. yes. reverting is not currently implemented and will be updated. 

3. the removeOnce is actually BR in the paper, and the scansideRemoval was not in the paper but after the paper relased I found that the scanside removing somewhat showed better cleaned map performance, so I added it to the code :)

Thank you. 
Giseop.

**Comment by crankler** [comment]
Yes, It's great to receive your explain! Thank you Giseop.
I've download the poses.txt and will try in a later.
The idea in your paper is right, we cann't get the most accurate data of true dynamics, but falsely-erasing statics is always a right way to class. 
Thank you again for your team's work!

By the way, I mentioned your tutor prof.ayoung and your lab for my supervisor ZhenZhong Jia this launch, he said they were classmates during  studying in Michigan，I don't know whether it's true, but it just seems interesting. 
I'll check this dataset and then the see the good result.

**Comment by gisbi-kim** [comment]
Interesting. Thank you and enjoy!

**Comment by crankler** [comment]
Sorry to bother again, can you tell me which pose file should I choose?
I've download the poses folder you mentioned and find there have 00.txt-10.txt（there have 11 file）, or can you share your pose.file， Thank you!

**Comment by gisbi-kim** [comment]
It depends on the pointcloud sequence what you want to use (i.e., a sequence that removes dynamics).
the pose file's sequence and the point cloud sequence name must be the same.
