### ISSUE TITLE
Removert for large sequences

### ISSUE THREAD

**Issue by Pallav1299** [irapkaist/removert#6]
First of all kudos for the great work. 

Is there any utility available to run removert for large maps in a single go (Considering the computation speed limitation)?

**Comment by gisbi-kim** [comment]
Hi @Pallav1299, thank you for considering using our work.

I empirically checked the number of map points ~ 5M points is feasible (it means~ 100scans if a scan has 50000 points, and can run ~ 10 scans per second for this setting)

so currently I recommend using a partial range of a long sequence (i.e., your own ROI where want to remove dynamics) 
see 
https://github.com/irapkaist/removert/blob/828753fed2aeb714b1af513eb06fd353cd4e0b5d/config/params_kitti.yaml#L52
and you can iterate this scan index range.

**Comment by Pallav1299** [comment]
@gisbi-kim, I planned to use removert for all scans, hence looking for a way to iterate through all the scans at once. 
I will try to do some modifications for the same if not already available.

**Comment by gisbi-kim** [comment]
Thank you. the function for iterating submaps is not yet implemented but under construction. 
I'll inform you later if the function is prepared.

Thank you!

Giseop.
