### ISSUE TITLE
Regarding Revert step in the implementation

### ISSUE THREAD

**Issue by humbletechy** [irapkaist/removert#7]
Hi,

I really appreciate the work you have done in the "Remove-then-Revert" publication and thanks for uploading its code. I was going through your code and stumbled upon the revert step. I wanted to ask, has this repository been updated to add the reverting steps or would it be done in future ?

**Comment by gisbi-kim** [comment]
Hi @humbletechy , thank you for having an interest in our work. 

The reverting function is under construction and will be updated soon (maybe Feb 2021)
sorry for the late update and I'll inform you later. 

Giseop.

**Comment by humbletechy** [comment]
Thanks for letting me know.

Regards,
Mehul Arora
