### ISSUE TITLE
Regarding number of points in the output point cloud.

### ISSUE THREAD

**Issue by humbletechy** [irapkaist/removert#8]
Hi @gisbi-kim, 

While I was going through the output of the "Removert", I found out that the number of points in the cleaned scans were less than the number of points in the original scan, could you please let me know if this is the case and what way did you use to upsample the point cloud to get the number of points same as the original point cloud.

Thanks, 
Regards,
Mehul Arora

**Comment by gisbi-kim** [comment]
see https://github.com/irapkaist/removert/blob/828753fed2aeb714b1af513eb06fd353cd4e0b5d/src/Removerter.cpp#L848

the number of original point = the number of this_scan_static + the number of this_scan_dynamic

if you preserve the number of the original input point cloud, 
for example, 
you can merge the this_scan_static and this_scan_dynamic 
with labeling them 0 and 1.

I hope this would be helpful.

**Comment by humbletechy** [comment]
So would it be required to remove the downsampling done to the original point cloud before that ?

**Comment by gisbi-kim** [comment]
yes, I think you can remove maybe this line. 
https://github.com/irapkaist/removert/blob/828753fed2aeb714b1af513eb06fd353cd4e0b5d/src/Removerter.cpp#L157

**Comment by humbletechy** [comment]
Ok thanks again.
